### ISSUE TITLE
[PE-D][Tester C] Sorting projects according to deadline displays incorrect date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F13-1/tp#165]
If I am not mistaken, this has to do with the date string but it is prioritising the Jan 2 date over the Jan 1 for me. 

![image.png](https://raw.githubusercontent.com/Josephaedan/ped/main/files/1f62e9be-2218-4db6-893c-57356c6e4f4b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Josephaedan/ped#3

**Comment by ConradLew** [comment]
Follows from #170 - the first `Jan 1 0001` and `Jan 2 0001` are created via `0000-01-01` and `0000-01-02` while the last `Jan 1 0001` is created by `0001-01-01`, so the internal order is correct although the UI representation is mixed up. Issue not explicitly mentioned in the bug report. @Donovan9617
