### ISSUE TITLE
[PE-D][Tester B] UG does not mention how to unpin a project, issue and clients

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F13-1/tp#168]
![image.png](https://raw.githubusercontent.com/eesung00/ped/main/files/9fd14e3e-ab9b-450a-89ca-a0c46c93deb0.png)

e.g. Didn't mentioned about how to unpin the project while it actually using the same command to unpin

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: eesung00/ped#9

**Comment by ConradLew** [comment]
Duplicate with #187
