### ISSUE TITLE
[PE-D][Tester F] Edit an existing person into another person is allowed causes Runtime Exception upon reopening

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F13-1/tp#169]
App allows the editing of Charlie into Dave with the exact same other fields 

### Before
![image.png](https://raw.githubusercontent.com/zylee348/ped/main/files/97d205fb-359b-4af0-b0cb-4ca409e92c29.png)

### After
![image.png](https://raw.githubusercontent.com/zylee348/ped/main/files/a341418e-64c7-4825-a5a6-8ffd66f01618.png)

### Fails to reopen

![image.png](https://raw.githubusercontent.com/zylee348/ped/main/files/675dd9c9-f769-42f2-9495-5e9096f1ba69.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: zylee348/ped#3

**Comment by ConradLew** [comment]
Duplicate with #205
