### ISSUE TITLE
[PE-D][Tester F] Allow addition of very long arguments

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F13-1/tp#193]
App permits addition of mobile numbers that are extremely long. Could be a vulnerability from a security point of view.

![image.png](https://raw.githubusercontent.com/zylee348/ped/main/files/e7b3b71e-3bbc-4c86-9334-52d876d86a2b.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: zylee348/ped#9

**Comment by Aishwarya-Hariharan-Iyer** [comment]
Noted! Initially, I had restricted the number to be between 8-10 digits (refer PR #72) but had thereupon removed the restriction as a precise upper limit/lower limit was hard to come by with a strong justification that does not violate preventing overzealous user input validation. However, this is certainly an aspect worth considering in future design decisions.
